version: '3'
services:
  backend:
    build:
      context: ./backend
      # dockerfile: backend/Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend

  frontend:
    build:
      context: ./frontend
      # dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
